# Generated by Django 4.0.3 on 2022-04-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coid', models.CharField(db_index=True, max_length=64, verbose_name='工作ID')),
                ('company_name', models.CharField(blank=True, max_length=264, null=True, verbose_name='公司名')),
                ('job_name', models.CharField(blank=True, max_length=264, null=True, verbose_name='岗位名字')),
                ('workarea_text', models.CharField(blank=True, max_length=264, null=True, verbose_name='工作地址')),
                ('providesalary_text', models.CharField(blank=True, max_length=264, null=True, verbose_name='薪资')),
                ('issuedate', models.CharField(blank=True, max_length=264, null=True, verbose_name='发布时间')),
                ('companytype_text', models.CharField(blank=True, max_length=264, null=True, verbose_name='公司类型')),
                ('companysize_text', models.CharField(blank=True, max_length=264, null=True, verbose_name='员工人数')),
                ('companyind_text', models.CharField(blank=True, max_length=264, null=True, verbose_name='所属行业')),
                ('job_href', models.CharField(blank=True, max_length=264, null=True, verbose_name='岗位连接')),
                ('jobwelf', models.CharField(blank=True, max_length=264, null=True, verbose_name='公司福利')),
                ('attribute_text', models.CharField(blank=True, max_length=264, null=True, verbose_name='岗位要求')),
                ('min_salary', models.FloatField(blank=True, null=True, verbose_name='最低薪资')),
                ('max_salary', models.FloatField(blank=True, null=True, verbose_name='最高薪资')),
                ('mean_salary', models.FloatField(blank=True, null=True, verbose_name='平均薪资')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='城市')),
                ('province', models.CharField(blank=True, max_length=128, null=True, verbose_name='省份')),
                ('education', models.CharField(blank=True, max_length=128, null=True, verbose_name='学历')),
            ],
        ),
    ]
