# Generated by Django 4.0.3 on 2022-03-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JDProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, verbose_name='商品ID')),
                ('p_name', models.CharField(blank=True, max_length=264, null=True, verbose_name='商品名')),
                ('p_price', models.FloatField(default=0, verbose_name='商品价格')),
                ('p_imag_scr', models.CharField(blank=True, max_length=264, null=True, verbose_name='商品图片')),
                ('p_shop', models.CharField(blank=True, max_length=264, null=True, verbose_name='店铺名')),
                ('p_comment_count', models.CharField(blank=True, max_length=264, null=True, verbose_name='评论数据')),
                ('p_sale', models.IntegerField(verbose_name='销量')),
                ('p_pinpai', models.CharField(blank=True, max_length=264, null=True, verbose_name='品牌')),
                ('p_detail', models.TextField(blank=True, null=True, verbose_name='商品详情')),
                ('p_gender', models.CharField(blank=True, max_length=24, null=True, verbose_name='性别')),
            ],
            options={
                'verbose_name': 'JD商品',
                'verbose_name_plural': 'JD商品',
                'db_table': 'jd_product_data',
            },
        ),
    ]
