# Generated by Django 4.0.3 on 2022-03-28 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Area', models.CharField(max_length=255)),
                ('Link', models.CharField(max_length=255)),
                ('Job_name', models.CharField(max_length=255)),
                ('Average', models.CharField(max_length=255)),
                ('Limit', models.CharField(max_length=255)),
                ('Request', models.CharField(max_length=255)),
                ('Demand', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'jobdata',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=100)),
                ('password_salt', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '访问de用户信息',
                'verbose_name_plural': '访问de用户信息',
                'db_table': 'Userip',
            },
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='home', max_length=30, verbose_name='页面名称')),
                ('count', models.IntegerField(default=0, verbose_name='页面访问次数')),
            ],
            options={
                'verbose_name': '各页面de访问次数',
                'verbose_name_plural': '各页面de访问次数',
                'db_table': 'VisitNumber',
            },
        ),
    ]
